set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(DC_ARM_CROSS_PREFIX "aarch64-linux-gnu" CACHE STRING "Cross-compiler prefix for ARM64 Linux")

if(NOT CMAKE_C_COMPILER)
    set(CMAKE_C_COMPILER "${DC_ARM_CROSS_PREFIX}-gcc")
endif()

if(NOT CMAKE_CXX_COMPILER)
    set(CMAKE_CXX_COMPILER "${DC_ARM_CROSS_PREFIX}-g++")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
