# Example parameters with small ranges
# AXI_ID_WIDTH 1-100
# BAUD_RATE 1-100
# CLK_FREQ 1-100
BUFFER_DEPTH 5-5
AXIS_DATA_WIDTH 16-64
AXI_ADDR_WIDTH 4-4
# ID_W_WIDTH 1-100
# ID_R_WIDTH 1-100
MAX_ROUTERS_X 4-4
# MAX_ROUTERS_X_WIDTH 1-100
MAX_ROUTERS_Y 4-4
# MAX_ROUTERS_Y_WIDTH 1-100
# AXI_MASTER_LOADER_FIFO_DEPTH 1-100
AXI_DATA_BYTES 4-4
# AXI_ID_WIDTH 1-100
# AXI_DEST_WIDTH 1-100
# AXI_USER_WIDTH 1-100
